[package]
name = "acme-proxy"
version = "0.2.0"
authors = ["Joel Linn <jl@conductive.de>"]
edition = '2018'

[dependencies]
actix-rt = "1.1"
actix-http = "2.0"
actix-web = "3.0"
clap = "2.33"
env_logger = "0.7"
log = "0.4"
regex = "1"

[profile.release]
lto = true
