[package]
name = "acme-proxy"
version = "1.0.0"
authors = ["Joel Linn <jl@conductive.de>"]
edition = '2018'

[dependencies]
actix-rt = "1"
actix-http = "2"
actix-web = "3"
clap = "2"
env_logger = "0.8"
log = "0.4"
regex = "1"

[profile.release]
lto = true
