[package]
name = "acme-proxy"
version = "0.0.1"
authors = ["Joel Linn <jl@conductive.de>"]
edition = '2018'

[dependencies]
actix-rt = "1.0"
actix-http = "1.0"
actix-web = "2.0"
clap = "2.33"
env_logger = "0.7"
log = "0.4"
regex = "1"
